/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Condition = string;
export interface DayDietPlan {
  'breakfast' : Array<Meal>,
  'nutritionalNotes' : string,
  'lunch' : Array<Meal>,
  'snack' : Array<Meal>,
  'dayNumber' : bigint,
  'dinner' : Array<Meal>,
}
export interface DietPlan {
  'dayDietPlans' : Array<DayDietPlan>,
  'patientId' : PatientId,
}
export type FoodItem = string;
export interface Meal {
  'fat' : number,
  'carbs' : number,
  'calories' : number,
  'name' : string,
  'description' : string,
  'protein' : number,
}
export interface MedicalReport {
  'status' : ReportStatus,
  'filename' : string,
  'filetype' : string,
  'uploadDate' : Time,
}
export interface Patient {
  'id' : PatientId,
  'age' : bigint,
  'bmi' : number,
  'dietaryPreferences' : Array<string>,
  'name' : string,
  'bloodSugar' : number,
  'detectedConditions' : Array<Condition>,
  'allergies' : Array<FoodItem>,
  'cholesterol' : number,
}
export type PatientId = bigint;
export type ReportStatus = { 'pending' : null } |
  { 'analyzed' : null } |
  { 'archived' : null };
export type Time = bigint;
export interface _SERVICE {
  'addPatient' : ActorMethod<
    [
      string,
      bigint,
      number,
      number,
      number,
      Array<FoodItem>,
      Array<string>,
      Array<Condition>,
    ],
    PatientId
  >,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getDietPlan' : ActorMethod<[PatientId], DietPlan>,
  'getPatient' : ActorMethod<[PatientId], Patient>,
  'getPatientReports' : ActorMethod<[PatientId], Array<MedicalReport>>,
  'saveDietPlan' : ActorMethod<[PatientId, Array<DayDietPlan>], undefined>,
  'uploadMedicalReport' : ActorMethod<
    [PatientId, string, string, ReportStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];