/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FoodItem = IDL.Text;
export const Condition = IDL.Text;
export const PatientId = IDL.Nat;
export const Patient = IDL.Record({
  'id' : PatientId,
  'age' : IDL.Nat,
  'bmi' : IDL.Float64,
  'dietaryPreferences' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'bloodSugar' : IDL.Float64,
  'detectedConditions' : IDL.Vec(Condition),
  'allergies' : IDL.Vec(FoodItem),
  'cholesterol' : IDL.Float64,
});
export const Meal = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'protein' : IDL.Float64,
});
export const DayDietPlan = IDL.Record({
  'breakfast' : IDL.Vec(Meal),
  'nutritionalNotes' : IDL.Text,
  'lunch' : IDL.Vec(Meal),
  'snack' : IDL.Vec(Meal),
  'dayNumber' : IDL.Nat,
  'dinner' : IDL.Vec(Meal),
});
export const DietPlan = IDL.Record({
  'dayDietPlans' : IDL.Vec(DayDietPlan),
  'patientId' : PatientId,
});
export const ReportStatus = IDL.Variant({
  'pending' : IDL.Null,
  'analyzed' : IDL.Null,
  'archived' : IDL.Null,
});
export const Time = IDL.Int;
export const MedicalReport = IDL.Record({
  'status' : ReportStatus,
  'filename' : IDL.Text,
  'filetype' : IDL.Text,
  'uploadDate' : Time,
});

export const idlService = IDL.Service({
  'addPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(FoodItem),
        IDL.Vec(IDL.Text),
        IDL.Vec(Condition),
      ],
      [PatientId],
      [],
    ),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getDietPlan' : IDL.Func([PatientId], [DietPlan], ['query']),
  'getPatient' : IDL.Func([PatientId], [Patient], ['query']),
  'getPatientReports' : IDL.Func(
      [PatientId],
      [IDL.Vec(MedicalReport)],
      ['query'],
    ),
  'saveDietPlan' : IDL.Func([PatientId, IDL.Vec(DayDietPlan)], [], []),
  'uploadMedicalReport' : IDL.Func(
      [PatientId, IDL.Text, IDL.Text, ReportStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FoodItem = IDL.Text;
  const Condition = IDL.Text;
  const PatientId = IDL.Nat;
  const Patient = IDL.Record({
    'id' : PatientId,
    'age' : IDL.Nat,
    'bmi' : IDL.Float64,
    'dietaryPreferences' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'bloodSugar' : IDL.Float64,
    'detectedConditions' : IDL.Vec(Condition),
    'allergies' : IDL.Vec(FoodItem),
    'cholesterol' : IDL.Float64,
  });
  const Meal = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const DayDietPlan = IDL.Record({
    'breakfast' : IDL.Vec(Meal),
    'nutritionalNotes' : IDL.Text,
    'lunch' : IDL.Vec(Meal),
    'snack' : IDL.Vec(Meal),
    'dayNumber' : IDL.Nat,
    'dinner' : IDL.Vec(Meal),
  });
  const DietPlan = IDL.Record({
    'dayDietPlans' : IDL.Vec(DayDietPlan),
    'patientId' : PatientId,
  });
  const ReportStatus = IDL.Variant({
    'pending' : IDL.Null,
    'analyzed' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Time = IDL.Int;
  const MedicalReport = IDL.Record({
    'status' : ReportStatus,
    'filename' : IDL.Text,
    'filetype' : IDL.Text,
    'uploadDate' : Time,
  });
  
  return IDL.Service({
    'addPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(FoodItem),
          IDL.Vec(IDL.Text),
          IDL.Vec(Condition),
        ],
        [PatientId],
        [],
      ),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getDietPlan' : IDL.Func([PatientId], [DietPlan], ['query']),
    'getPatient' : IDL.Func([PatientId], [Patient], ['query']),
    'getPatientReports' : IDL.Func(
        [PatientId],
        [IDL.Vec(MedicalReport)],
        ['query'],
      ),
    'saveDietPlan' : IDL.Func([PatientId, IDL.Vec(DayDietPlan)], [], []),
    'uploadMedicalReport' : IDL.Func(
        [PatientId, IDL.Text, IDL.Text, ReportStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };