/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Meal {
    fat: number;
    carbs: number;
    calories: number;
    name: string;
    description: string;
    protein: number;
}
export type Time = bigint;
export interface DayDietPlan {
    breakfast: Array<Meal>;
    nutritionalNotes: string;
    lunch: Array<Meal>;
    snack: Array<Meal>;
    dayNumber: bigint;
    dinner: Array<Meal>;
}
export interface DietPlan {
    dayDietPlans: Array<DayDietPlan>;
    patientId: PatientId;
}
export type Condition = string;
export type FoodItem = string;
export interface MedicalReport {
    status: ReportStatus;
    filename: string;
    filetype: string;
    uploadDate: Time;
}
export type PatientId = bigint;
export interface Patient {
    id: PatientId;
    age: bigint;
    bmi: number;
    dietaryPreferences: Array<string>;
    name: string;
    bloodSugar: number;
    detectedConditions: Array<Condition>;
    allergies: Array<FoodItem>;
    cholesterol: number;
}
export enum ReportStatus {
    pending = "pending",
    analyzed = "analyzed",
    archived = "archived"
}
export interface backendInterface {
    addPatient(name: string, age: bigint, bmi: number, bloodSugar: number, cholesterol: number, allergies: Array<FoodItem>, dietaryPreferences: Array<string>, detectedConditions: Array<Condition>): Promise<PatientId>;
    getAllPatients(): Promise<Array<Patient>>;
    getDietPlan(patientId: PatientId): Promise<DietPlan>;
    getPatient(id: PatientId): Promise<Patient>;
    getPatientReports(patientId: PatientId): Promise<Array<MedicalReport>>;
    saveDietPlan(patientId: PatientId, dayDietPlans: Array<DayDietPlan>): Promise<void>;
    uploadMedicalReport(patientId: PatientId, filename: string, filetype: string, status: ReportStatus): Promise<void>;
}
import type { MedicalReport as _MedicalReport, ReportStatus as _ReportStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addPatient(arg0: string, arg1: bigint, arg2: number, arg3: number, arg4: number, arg5: Array<FoodItem>, arg6: Array<string>, arg7: Array<Condition>): Promise<PatientId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getDietPlan(arg0: PatientId): Promise<DietPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietPlan(arg0);
            return result;
        }
    }
    async getPatient(arg0: PatientId): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return result;
        }
    }
    async getPatientReports(arg0: PatientId): Promise<Array<MedicalReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientReports(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientReports(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDietPlan(arg0: PatientId, arg1: Array<DayDietPlan>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDietPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDietPlan(arg0, arg1);
            return result;
        }
    }
    async uploadMedicalReport(arg0: PatientId, arg1: string, arg2: string, arg3: ReportStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMedicalReport(arg0, arg1, arg2, to_candid_ReportStatus_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMedicalReport(arg0, arg1, arg2, to_candid_ReportStatus_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_MedicalReport_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicalReport): MedicalReport {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReportStatus;
    filename: string;
    filetype: string;
    uploadDate: _Time;
}): {
    status: ReportStatus;
    filename: string;
    filetype: string;
    uploadDate: Time;
} {
    return {
        status: from_candid_ReportStatus_n4(_uploadFile, _downloadFile, value.status),
        filename: value.filename,
        filetype: value.filetype,
        uploadDate: value.uploadDate
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    analyzed: null;
} | {
    archived: null;
}): ReportStatus {
    return "pending" in value ? ReportStatus.pending : "analyzed" in value ? ReportStatus.analyzed : "archived" in value ? ReportStatus.archived : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicalReport>): Array<MedicalReport> {
    return value.map((x)=>from_candid_MedicalReport_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ReportStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    pending: null;
} | {
    analyzed: null;
} | {
    archived: null;
} {
    return value == ReportStatus.pending ? {
        pending: null
    } : value == ReportStatus.analyzed ? {
        analyzed: null
    } : value == ReportStatus.archived ? {
        archived: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
